Repository yiisoft/files, pull requests merged in 2020-11, with the labels that each got.

#17 Improve method filterPath + other enhancements
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  README.md
  phpunit.xml.dist
  src/FileHelper.php
  tests/FileHelperTest.php
Labels: status:code review

#23 Fixing unlink() under Windows
  tests/FileHelperTest.php
Labels: type:bug

#24 Add FileHelper::isEmptyDirectory() and improve FileHelper::unlink()
  src/FileHelper.php
  tests/FileHelperTest.php
Labels: status:code review

#26 Add FileHelper::lastModifiedTime().
  src/FileHelper.php
  tests/FileHelperTest.php
Labels: type:enhancement

#22 Replace FileHelper::filterPath to PathMatcher
  composer.json
  src/FileHelper.php
  src/PathMatcher/PathMatcher.php
  src/PathMatcher/PathMatcherInterface.php
  src/PathMatcher/PathPattern.php
  tests/FileHelperCopyDirectoryTest.php
  tests/FileHelperTest.php
  tests/FileSystemTestCase.php
  tests/PathMatcher/PathMatcherTest.php
  tests/PathMatcher/PathPatternTest.php
Labels: status:ready for merge

#34 Adopt psalm, add tests and minor fixes
  psalm.xml
  src/FileHelper.php
  tests/FileHelperTest.php
Labels: status:code review
